# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancoamaro', '0002_auto_20160326_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('tipo_op', models.IntegerField(default=0)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancoamaro.Cliente')),
            ],
        ),
    ]
